# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='bodytext',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
    ]
